# btarg device settings, YAML
# With exception of 'general', each top level key defines a new ioc for that device
general:
    prefix: TGT:LAB
    log_dir: 'logs'   # path of logs directory
    #epics_addr_list: '129.57.86.255'  # In Hall B
    epics_addr_list: '127.255.255.255'  # On experimental equipment network
    #epics_beacon_addr_list: '127.255.255.255'
    delay: 0.5
pfeiffer-26x_1:
    module: 'devices.tpg_26x'
    autostart: True
    ip: '129.57.37.103'
    port: '1001'            # channel 1 of serial to ethernet
    timeout: 2
    delay: 5
    channels:
        - Outlet_PI
pfeiffer-26x_2:
    module: 'devices.tpg_26x'
    autostart: True
    ip: '129.57.37.103'
    port: '1002'            # channel 2 of serial to ethernet
    timeout: 2
    delay: 5
    channels:
        - Inlet_PI
si9700:
    module: 'devices.si9700'
    autostart: True
    ip: '129.57.37.103'
    port: '1003'            # channel 3 of serial to ethernet
    timeout: 2
    delay: 5
    channels:
        - Liquifier_TI
        - None
lakeshore_218_1:
    module: 'devices.ls218'
    autostart: True          # Should IOC Manager try to start this?
    ip: '192.168.1.107'
    port: '1002'    # channel 1 of serial to ethernet
    timeout: 2
    delay: 2
    channels:   # List of PV names for each read channel of 218 in order
        - Cell_TI
        - Condenser_TI
        - None
        - None
        - Shield_DS_TI
        - Shield_Plate_TI
        - Evaporator_Out_TI
        - None
rigol_dp832:
    module: 'devices.dp832'
    autostart: True          # Should IOC Manager try to start this?
    ip: '192.168.1.32'
    port: '5555'
    timeout: 2
    delay: 5
    voltage_limit: 30.0
    channels: # List of channel names in order. None indicates unused channel.
        - Reservoir_Heater
        - Shield_Heater

